name: Build and Deploy to Minikube
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker to use Minikube's environment
      run: |
        minikube -p minikube docker-env | Invoke-Expression
    - name: Build Docker image
      run: |
        docker build -t zeeshan2646/my-app:latest .
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Push Docker image to Docker Hub
      run: docker push zeeshan2646/my-app:latest
    - name: Create namespace
      run: |
        kubectl create namespace my-app-ns --dry-run=client -o yaml | kubectl apply -f -
    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml